### ISSUE TITLE
Add default Issue, PR & Codeowner template files

### ISSUE THREAD

**Issue by mikemimik** [npm/open-source-project-boilerplate#1]
Discussion around our default template files used for projects moving forward.

Files in question:
- `.github/ISSUE_TEMPLATE.md`
- `.github/PULL_REQUEST_TEMPLATE.md`
- `.github/CODEOWNERS.md`

**Comment by darcyclarke** [comment]
@mikemimik these files/defaults don't seem to get picked up when we utilize the `settings.yml` extends... wondering if there's something specific we have to add/do inside that file to ensure these get mapped/used by our projects (and/or maybe there's a limitation there)

**Comment by mikemimik** [comment]
@darcyclarke that’s odd. I can poke at this a little and see what the issue is in my spare time

**Comment by claudiahdz** [comment]
@darcyclarke Picking up this issue. It seems we can't just extend issue templates using `settings.yml`. Github does allow though creating a public repository `.github` on the org that will extend default config and settings to any repo created on said org (https://help.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file). I'm not sure that's what we actually since the npm org is broad and we might want specific defaults for our public-facing repos and other for the private ones.

**Comment by claudiahdz** [comment]
> It seems we can't just extend issue templates using settings.yml

I stand corrected. Found the way to extend templates with `settings.yml`:
```
# issue template
_extends: .github:ISSUE_TEMPLATE.md

# pr template
_extends: .github:PULL_REQUEST_TEMPLATE.md

# code owners
_extends: .github:CODEOWNERS.md
```

**Comment by claudiahdz** [comment]
I'm out of sync, looks like we already have this going on: https://github.com/npm/.github/tree/master/.github

**Comment by claudiahdz** [comment]
@darcyclarke Considering we have a `defaults` [repo](https://github.com/npm/.github) that actually extends every repo on the npm org... I wonder, shouldn't we use that one instead of this repo? Do we want to have a boilerplate for the CLI repos and another for registry repos? Does it make sense to have both repos going on? 

We should also consider that it seems configuration files are the only ones that can be shared with probot and this repo `create-oss` can't extend markdown templates either way.
